# Generated by Django 5.1.7 on 2025-03-18 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0005_auditlog_product_min_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('income', 'Daromad'), ('expense', 'Xarajat')], max_length=10)),
                ('amount', models.FloatField(default=0, verbose_name='Summa')),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.movement')),
                ('reservoir_movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.reservoirmovement')),
            ],
        ),
    ]
