# Generated by Django 5.1.7 on 2025-03-22 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('warehouse', '0002_localmovement_difference_ton_localmovement_doc_ton_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financeoperation',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='financeoperation',
            name='note',
        ),
        migrations.RemoveField(
            model_name='financeoperation',
            name='reservoir_movement',
        ),
        migrations.AddField(
            model_name='financeoperation',
            name='amount_sum',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='financeoperation',
            name='local_movement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.localmovement'),
        ),
        migrations.AlterField(
            model_name='financeoperation',
            name='movement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.movement'),
        ),
    ]
