# Generated by Django 5.1.7 on 2025-03-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_remove_financeoperation_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeoperation',
            name='doc_fact_diff',
            field=models.BooleanField(default=False),
        ),
    ]
