# Generated by Django 5.1.7 on 2025-03-23 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_financeoperation_doc_fact_diff'),
        ('warehouse', '0002_localmovement_difference_ton_localmovement_doc_ton_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('movement_type', models.CharField(choices=[('in', 'Kirim'), ('out', 'Chiqim')], max_length=3)),
                ('quantity', models.FloatField(default=0)),
                ('total_price_usd', models.FloatField(default=0)),
                ('total_price_sum', models.FloatField(default=0)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.product')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse')),
            ],
            options={
                'verbose_name': 'Moliyaviy yozuv',
                'verbose_name_plural': 'Moliyaviy yozuvlar',
                'ordering': ['-date'],
            },
        ),
        migrations.DeleteModel(
            name='FinanceOperation',
        ),
    ]
