# Generated by Django 5.1.7 on 2025-03-15 13:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Kod')),
                ('name', models.CharField(max_length=100, verbose_name='Mahsulot nomi')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kategoriya')),
                ('volume', models.FloatField(default=0, verbose_name='Hajmi (l)')),
                ('weight', models.FloatField(default=0, verbose_name="Og'irligi (kg)")),
                ('price_usd', models.FloatField(default=0, verbose_name='Narx (USD)')),
                ('price_sum', models.FloatField(default=0, verbose_name="Narx (so'm)")),
                ('in_qty', models.FloatField(default=0, verbose_name='Umumiy kirim (qty)')),
                ('out_qty', models.FloatField(default=0, verbose_name='Umumiy chiqim (qty)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Wagon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wagon_number', models.CharField(max_length=20, unique=True, verbose_name='Vagon raqami')),
                ('wagon_type', models.CharField(max_length=50, verbose_name='Vagon turi')),
                ('net_weight', models.FloatField(default=0, verbose_name="Netto og'irligi")),
                ('meter_weight', models.FloatField(default=0, verbose_name="Meter og'irligi")),
                ('capacity', models.FloatField(default=0, verbose_name="Sig'im (tonna)")),
                ('volume', models.FloatField(default=0, verbose_name='Hajmi (L)')),
                ('price_sum', models.FloatField(default=0, verbose_name="Umumiy summa (so'm)")),
                ('condition', models.CharField(default='Yaxshi', max_length=50, verbose_name='Holati')),
            ],
            options={
                'ordering': ['wagon_number'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ombor nomi')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Manzil')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0, verbose_name='Qoldiq (qty)')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='warehouse.product', verbose_name='Mahsulot')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse', verbose_name='Ombor'),
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Hujjat raqami')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Sana')),
                ('movement_type', models.CharField(choices=[('in', 'Kirim'), ('out', 'Chiqim')], max_length=3, verbose_name='Harakat turi')),
                ('quantity', models.FloatField(verbose_name='Miqdor (qty)')),
                ('price_sum', models.FloatField(default=0, verbose_name="Narx (so'm)")),
                ('note', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.product', verbose_name='Mahsulot')),
                ('wagon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.wagon', verbose_name='Vagon')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse', verbose_name='Ombor')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
