# Generated by Django 5.1.7 on 2025-03-15 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50, verbose_name='Partiya raqami')),
                ('manufacture_date', models.DateField(blank=True, null=True, verbose_name='Ishlab chiqarilgan sana')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Yaroqlilik muddati')),
                ('in_qty', models.FloatField(default=0, verbose_name='Kirim (qty)')),
                ('out_qty', models.FloatField(default=0, verbose_name='Chiqim (qty)')),
                ('quantity', models.FloatField(default=0, verbose_name='Joriy qoldiq (qty)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.product', verbose_name='Mahsulot')),
            ],
            options={
                'unique_together': {('product', 'batch_number')},
            },
        ),
        migrations.AddField(
            model_name='movement',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.batch', verbose_name='Partiya'),
        ),
    ]
