# Generated by Django 5.1.7 on 2025-03-20 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localmovement',
            name='difference_ton',
            field=models.FloatField(default=0, editable=False, verbose_name='Farq (ton)'),
        ),
        migrations.AddField(
            model_name='localmovement',
            name='doc_ton',
            field=models.FloatField(default=0, verbose_name="Hujjat bo'yicha ton"),
        ),
        migrations.AddField(
            model_name='localmovement',
            name='fact_ton',
            field=models.FloatField(default=0, verbose_name='Fakt ton'),
        ),
        migrations.AddField(
            model_name='localmovement',
            name='specific_weight',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Udel og‘irlik'),
        ),
        migrations.AlterField(
            model_name='localmovement',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.product', verbose_name='Mahsulot'),
        ),
        migrations.AlterField(
            model_name='localmovement',
            name='temperature',
            field=models.FloatField(default=0, verbose_name='Harorat (°C)'),
        ),
        migrations.AlterField(
            model_name='localmovement',
            name='wagon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.wagon', verbose_name='Vagon'),
        ),
    ]
