# Generated by Django 5.1.7 on 2025-03-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_batch_movement_batch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'verbose_name': 'Партия', 'verbose_name_plural': 'Партиялар'},
        ),
        migrations.AlterField(
            model_name='product',
            name='price_sum',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name="Narx (so'm)"),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_usd',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Narx (USD)'),
        ),
    ]
