# Generated by Django 5.1.7 on 2025-03-17 11:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_alter_batch_options_alter_product_price_sum_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Rezervuar nomi')),
                ('capacity', models.FloatField(default=0, verbose_name="Sig'im (L yoki tonna)")),
                ('in_qty', models.FloatField(default=0, verbose_name='Kirim (qty)')),
                ('out_qty', models.FloatField(default=0, verbose_name='Chiqim (qty)')),
                ('quantity', models.FloatField(default=0, verbose_name='Joriy qoldiq (qty)')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.product', verbose_name='Saqlanayotgan mahsulot')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse', verbose_name='Ombor')),
            ],
        ),
        migrations.CreateModel(
            name='ReservoirMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Sana')),
                ('movement_type', models.CharField(choices=[('in', "Kirim (to'ldirish)"), ('out', "Chiqim (bo'shatish)")], max_length=3, verbose_name='Harakat turi')),
                ('quantity', models.FloatField(verbose_name='Miqdor (qty)')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.product', verbose_name='Mahsulot')),
                ('reservoir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.reservoir', verbose_name='Rezervuar')),
            ],
        ),
    ]
