# Generated by Django 5.1.7 on 2025-03-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_auditlog_product_min_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='zone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Zona'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='location_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Location Code'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='zone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Zona'),
        ),
    ]
