# Generated by Django 5.1.7 on 2025-03-19 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_product_zone_warehouse_location_code_warehouse_zone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'verbose_name': 'Audit log', 'verbose_name_plural': 'Audit logs'},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': 'Инвентарь', 'verbose_name_plural': 'Инвентарь'},
        ),
        migrations.AlterModelOptions(
            name='movement',
            options={'ordering': ['-date'], 'verbose_name': 'Движение', 'verbose_name_plural': 'Движения'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['code'], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
        migrations.AlterModelOptions(
            name='reservoir',
            options={'verbose_name': 'Rezervuar', 'verbose_name_plural': 'Rezervuarlar'},
        ),
        migrations.AlterModelOptions(
            name='reservoirmovement',
            options={'verbose_name': 'Rezervuar harakati', 'verbose_name_plural': 'Rezervuar harakatlari'},
        ),
        migrations.AlterModelOptions(
            name='wagon',
            options={'ordering': ['wagon_number'], 'verbose_name': 'Вагон', 'verbose_name_plural': 'Вагонлар'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name': 'склад', 'verbose_name_plural': 'склады'},
        ),
    ]
