# Generated by Django 5.1.7 on 2025-03-20 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_alter_auditlog_options_alter_inventory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='reservoir',
            options={},
        ),
        migrations.AlterModelOptions(
            name='reservoirmovement',
            options={},
        ),
        migrations.AlterModelOptions(
            name='wagon',
            options={'ordering': ['wagon_number']},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={},
        ),
    ]
