# Generated by Django 5.1.7 on 2025-03-20 07:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_alter_auditlog_options_alter_inventory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Klient nomi')),
            ],
            options={
                'verbose_name': 'Klient',
                'verbose_name_plural': 'Klientlar',
            },
        ),
        migrations.AlterModelOptions(
            name='wagon',
            options={'ordering': ['wagon_number'], 'verbose_name': 'Вагон', 'verbose_name_plural': 'Вагонлар'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name': 'Ombor', 'verbose_name_plural': 'Omborlar'},
        ),
        migrations.AddField(
            model_name='product',
            name='density',
            field=models.FloatField(default=0, verbose_name='Zichligi (Удел Факт)'),
        ),
        migrations.AddField(
            model_name='product',
            name='temperature',
            field=models.FloatField(default=0, verbose_name='Harorat (°C)'),
        ),
        migrations.AddField(
            model_name='wagon',
            name='smgs_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SMGS raqami'),
        ),
        migrations.CreateModel(
            name='LocalMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Sana')),
                ('density', models.FloatField(default=0, verbose_name='Zichlik (Удел)')),
                ('temperature', models.FloatField(default=0, verbose_name='Harorat')),
                ('liter', models.FloatField(default=0, verbose_name='Litr')),
                ('mass', models.FloatField(default=0, verbose_name='Massa (kg)')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.localclient', verbose_name='Klient')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.product', verbose_name='Mahsulot')),
                ('wagon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.wagon', verbose_name='Vagon')),
            ],
            options={
                'verbose_name': 'Harakat',
                'verbose_name_plural': 'Harakatlar',
            },
        ),
    ]
