# Generated by Django 5.1.7 on 2025-03-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_localclient_alter_wagon_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movement',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='product',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='wagon',
            name='smgs_number',
        ),
        migrations.AddField(
            model_name='movement',
            name='density',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Zichlik'),
        ),
        migrations.AddField(
            model_name='movement',
            name='liter',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Litr'),
        ),
        migrations.AddField(
            model_name='movement',
            name='specific_weight',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name="Udel og'irlik"),
        ),
        migrations.AddField(
            model_name='product',
            name='specific_weight',
            field=models.FloatField(default=0, verbose_name="Udel Og'irligi"),
        ),
        migrations.AlterField(
            model_name='product',
            name='density',
            field=models.FloatField(default=0, verbose_name='Zichlik (kg/l)'),
        ),
    ]
