# Generated by Django 5.1.7 on 2025-03-20 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0010_remove_movement_batch_remove_product_temperature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.batch', verbose_name='Parтия'),
        ),
    ]
